### ISSUE TITLE
hi，i cannot read your paper on Neurlps Website,please send me the paper of this code ,thanks!

### ISSUE THREAD

**Issue by twythebest** [Armagaan/GraphTrail#1]
hi，i cannot read your paper ,please send me the paper of this code  to eamil adress :twythebest@gmail.com,thanks!

**Comment by huduo0713** [comment]
> hi，i cannot read your paper ,please send me the paper of this code to eamil adress :[twythebest@gmail.com](mailto:twythebest@gmail.com),thanks!

Hi, did the author send you this paper? I'm also interested in this work, if he sent it to you please send me a copy to my email:huduo0713@gmail.com, thank you!

**Comment by twythebest** [comment]
no，he didn‘t

**Comment by huduo0713** [comment]
> no，he didn‘t

Well, maybe the author hasn't seen it yet.

**Comment by Armagaan** [comment]
Hi, I've added a link in the repo's readme. Let me know if you face any issues. Sorry, I had not checked GitHub notifications in a while.
